"""Add creator_id to Exam model

Revision ID: 60e22ee4674a
Revises: 80e4dd0bd140
Create Date: 2025-02-26 23:41:23.358645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e22ee4674a'
down_revision = '80e4dd0bd140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_exam_creator_id', 'users', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_constraint('fk_exam_creator_id', type_='foreignkey')
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###
