"""Describe your changes here

Revision ID: 80e4dd0bd140
Revises: 847123e86636
Create Date: 2025-02-26 18:57:36.837086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e4dd0bd140'
down_revision = '847123e86636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_key', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('blockchain_address', sa.String(length=42), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('blockchain_address')
        batch_op.drop_column('public_key')

    # ### end Alembic commands ###
